controller_manager:
  ros__parameters:
    update_rate: 50
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50
    arm_controller:
      type: position_controllers/JointTrajectoryController
      joints:
        - joint1
        - joint2
        - joint3
        - joint4
        - joint5
        - joint6
      state_publish_rate: 50
      action_monitor_rate: 10
      constraints:
        goal_time: 0.5
        stopped_velocity_tolerance: 0.01
        joint1: {trajectory: 0.05, goal: 0.02}
        joint2: {trajectory: 0.05, goal: 0.02}
        joint3: {trajectory: 0.05, goal: 0.02}
        joint4: {trajectory: 0.05, goal: 0.02}
        joint5: {trajectory: 0.05, goal: 0.02}
        joint6: {trajectory: 0.05, goal: 0.02}
      gains:
        joint1: {p: 100.0, d: 10.0, i: 1.0}
        joint2: {p: 100.0, d: 10.0, i: 1.0}
        joint3: {p: 100.0, d: 10.0, i: 1.0}
        joint4: {p: 100.0, d: 10.0, i: 1.0}
        joint5: {p: 100.0, d: 10.0, i: 1.0}
        joint6: {p: 100.0, d: 10.0, i: 1.0}

